version: '3.5.7'
services:
  netbox:
    ports:
      - "51234:8080"
    # If you want the Nginx unit status page visible from the
    # outside of the container add the following port mapping:
    # - "8001:8081"
    # healthcheck:
      # Time for which the health check can fail after the container is started.
      # This depends mostly on the performance of your database. On the first start,
      # when all tables need to be created the start_period should be higher than on
      # subsequent starts. For the first start after major version upgrades of NetBox
      # the start_period might also need to be set higher.
      # Default value in our docker-compose.yml is 60s
      # start_period: 90s
    healthcheck:
      retries: 15
    volumes:
    - netbox-configuration:/etc/netbox/config:z,ro
    extends:
      file: docker-compose.yml
      service: netbox
  postgres:
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data
    extends:
      file: docker-compose.yml
      service: postgres
  redis:
    volumes:
    - netbox-redis-data:/data
    extends:
      file: docker-compose.yml
      service: redis
  redis-cache:
    volumes:
    - netbox-redis-cache-data:/data
    extends:
      file: docker-compose.yml
      service: redis-cache
