version: '3.4'
services:
  netbox:
    ports:
    - 51234:8080
    volumes:
    - /volume1/docker/netbox-data/configuration:/etc/netbox/config:z,ro
    healthcheck:
      retries: 15
  netbox-worker:
    volumes:
    - /volume1/docker/netbox-data/configuration:/etc/netbox/config:z,ro
  netbox-housekeeping:
    volumes:
    - /volume1/docker/netbox-data/configuration:/etc/netbox/config:z,ro
  postgres:
    volumes:
    -  /volume1/docker/netbox-data/netbox-postgres-data:/var/lib/postgresql/data
  redis:
    volumes:
    -  /volume1/docker/netbox-data/netbox-redis-data:/data
  redis-cache:
    volumes:
    -  /volume1/docker/netbox-data/netbox-redis-cache-data:/data
