version: '3.5.7'
services:
  netbox:
    ports:
      - "51234:8080"
    # If you want the Nginx unit status page visible from the
    # outside of the container add the following port mapping:
    # - "8001:8081"
    # healthcheck:
      # Time for which the health check can fail after the container is started.
      # This depends mostly on the performance of your database. On the first start,
      # when all tables need to be created the start_period should be higher than on
      # subsequent starts. For the first start after major version upgrades of NetBox
      # the start_period might also need to be set higher.
      # Default value in our docker-compose.yml is 60s
      # start_period: 90s
    healthcheck:
      retries: 15
    volumes:
    - netbox-data/netbox-data/configuration:/etc/netbox/config:z,ro
    - netbox-data/netbox-data/netbox-data/media:/opt/netbox/netbox/media:z,rw
    - netbox-data/netbox-data/netbox-data/reports:/opt/netbox/netbox/reports:z,rw
    - netbox-data/netbox-data/netbox-data/scripts/:/opt/netbox/netbox/scripts:z,rw
  postgres:
    volumes:
    - netbox-data/netbox-data/netbox-postgres-data:/var/lib/postgresql/data
  redis:
    volumes:
    - netbox-data/netbox-data/netbox-redis-data:/data
  redis-cache:
    volumes:
    - netbox-data/netbox-data/netbox-redis-cache-data:/data
